name         'puppet-module-fixleapsecond'
version      '0.0.1'
source       'git@github.com:kylefu8/puppet-module-fixleapsecond.git'
author       'Kyle Fu'
license      'Apache License, Version 2.0'
summary      'Work around to avoid leap second'
description  'Work around to avoid leap second bug on RHEL and SUSE.'
project_page 'https://github.com/kylefu8/puppet-module-fixleapsecond'

dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'ghoneycutt/common', '>= 1.0.0'
